on:
  release:
    types: [published]
  push:
    branches: [main]
    tags: [v*]

jobs:
  push-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

# no need to run tests as during a pull request they have been already ran
#
#      - name: 'Waiting for tests to pass'
#        uses: lewagon/wait-on-check-action@v1.0.0
#        with:
#          ref: ${{ github.ref }}
#          check-name: checks
#          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Login to the Dockerhub'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      - name: 'Build and Push the image to the Dockerhub'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ./Docker/Dockerfile
          tags: trickman/googlesheet-monitoring-tg-bot:latest

